const scripts=[
{id:"01",title:"Réussirez-vous à sortir ?",category:"loisirs",sector:"Escape game",objective:"Générer des réservations",angle:"Faire vivre la tension d’une mission sans dévoiler les énigmes.",format:"Voix off + montage immersif",duration:"30 s",problem:"L’expérience reste abstraite tant que le prospect ne ressent pas son intensité.",hook:"Vous avez 60 minutes. Cette porte est votre seule sortie.",beats:["La porte se verrouille. Le chrono démarre à 60:00.","Cadenas, indice caché et regards entre joueurs en coupes rapides.","Voix off : « Chaque détail compte. Chaque seconde aussi. »","CTA : « Votre équipe pense pouvoir sortir ? Réservez votre mission. »"]},
{id:"02",title:"Le virage que personne n’oublie",category:"loisirs",sector:"Circuit de karting",objective:"Vendre une session découverte",angle:"Faire ressentir la vitesse à travers un virage signature du circuit.",format:"POV + texte écran",duration:"15 s",problem:"Les images de piste se ressemblent et ne transmettent pas la sensation de conduite.",hook:"À 52 km/h, ce virage paraît beaucoup plus serré.",beats:["Caméra embarquée à l’approche du virage.","Freinage, point de corde et accélération avec son moteur.","Classement qui s’affiche à l’arrivée.","CTA : « Votre chrono vous attend. Réservez votre session. »"]},
{id:"03",title:"Un anniversaire sans temps mort",category:"loisirs",sector:"Parc de loisirs",objective:"Obtenir des demandes anniversaire",angle:"Montrer le soulagement des parents autant que l’expérience des enfants.",format:"Montage journée + voix off",duration:"30 s",problem:"Les parents craignent une organisation compliquée et des enfants difficiles à occuper.",hook:"Dix enfants, deux heures et rien à organiser : voici le programme.",beats:["Accueil du groupe et remise des bracelets.","Trois activités en montage rythmé.","Goûter déjà préparé et bougies.","CTA : « Choisissez la date, on s’occupe du reste. »"]},
{id:"04",title:"Votre cerveau croit que c’est réel",category:"loisirs",sector:"Salle de réalité virtuelle",objective:"Attirer de nouveaux joueurs",angle:"Filmer les réactions physiques avant de révéler ce que voit le casque.",format:"Réaction + capture de jeu",duration:"30 s",problem:"Les personnes qui n’ont jamais testé la VR sous-estiment l’immersion.",hook:"Il sait que le sol est plat. Son cerveau, lui, n’est plus d’accord.",beats:["Joueur hésitant au bord d’un vide virtuel.","Réaction des amis hors champ.","Alternance entre capture du jeu et mouvements réels.","CTA : « Il faut le vivre pour le croire. Réservez votre expérience. »"]},
{id:"05",title:"Le défi parfait pour votre équipe",category:"loisirs",sector:"Activité team building",objective:"Générer des demandes B2B",angle:"Transformer une activité ludique en démonstration de cohésion.",format:"Mini-reportage",duration:"45 s",problem:"Les entreprises cherchent une activité qui ne ressemble pas à une réunion déguisée.",hook:"On leur a retiré leurs bureaux. Voilà comment ils ont recommencé à communiquer.",beats:["Présentation rapide du défi collectif.","Équipe en réflexion puis en action.","Réaction d’un participant après la réussite.","CTA : « Votre prochain souvenir d’équipe commence ici. »"]},

{id:"06",title:"Ce plat disparaît dimanche",category:"restauration",sector:"Restaurant indépendant",objective:"Remplir les services de la semaine",angle:"Créer une raison immédiate de venir avec une assiette éphémère.",format:"Chef face caméra + cuisine",duration:"30 s",problem:"Les nouveautés de la carte ne sont pas toujours vues par les clients réguliers.",hook:"Dimanche soir, ce plat disparaît de notre carte.",beats:["Le chef présente l’ingrédient principal.","Cuisson, sauce et dressage en plans courts.","Texte écran : « Produit local • quantité limitée ».","CTA : « Disponible jusqu’à dimanche. Réservez votre table. »"]},
{id:"07",title:"Trois jours pour un croissant",category:"restauration",sector:"Boulangerie artisanale",objective:"Valoriser la qualité",angle:"Rendre visible le temps caché derrière un produit familier.",format:"Voix off + gestes métier",duration:"45 s",problem:"Un croissant artisanal peut sembler comparable à un produit industriel.",hook:"Ce croissant demande trois jours de travail. Voici pourquoi.",beats:["Jour 1 : pâte et premier repos.","Jour 2 : tourage du beurre en gros plan.","Jour 3 : façonnage, pousse et four.","CTA : « Venez goûter ce que trois jours de patience changent. »"]},
{id:"08",title:"La pizza qui arrive avant votre série",category:"restauration",sector:"Pizzeria",objective:"Augmenter les commandes directes",angle:"Comparer le temps de livraison à une habitude du quotidien.",format:"Chronomètre + montage",duration:"15 s",problem:"Les clients commandent via des plateformes et ignorent le service direct.",hook:"Votre épisode n’aura pas commencé que votre pizza sera déjà en route.",beats:["Commande passée sur le site avec chrono.","Pâte garnie puis four.","Livreur qui ferme son sac.","CTA : « Commandez en direct ce soir. »"]},
{id:"09",title:"Votre café a une adresse",category:"restauration",sector:"Coffee shop",objective:"Créer du trafic local",angle:"Raconter l’origine du grain en partant de la tasse servie.",format:"Barista face caméra",duration:"30 s",problem:"Le café de spécialité paraît complexe ou réservé aux connaisseurs.",hook:"Cette tasse commence à 8 000 kilomètres d’ici.",beats:["Tasse posée devant la caméra.","Carte rapide de l’origine du grain.","Extraction et lait texturé.","CTA : « Venez le découvrir, on vous explique sans jargon. »"]},
{id:"10",title:"Le déjeuner de 40 personnes",category:"restauration",sector:"Traiteur",objective:"Obtenir des devis entreprise",angle:"Montrer l’organisation invisible derrière un événement fluide.",format:"Coulisses + chiffres écran",duration:"45 s",problem:"Les entreprises évaluent mal la fiabilité d’un traiteur avant le jour J.",hook:"À midi, 40 personnes mangeront ici. À 9 h, la salle est encore vide.",beats:["Cuisine en préparation à 9 h.","Transport, installation et contrôles.","Buffet prêt avant l’arrivée des invités.","CTA : « Votre prochain événement mérite la même sérénité. »"]},

{id:"11",title:"Une bague qui n’existait pas",category:"artisan",sector:"Bijouterie",objective:"Valoriser le sur-mesure",angle:"Transformer une histoire personnelle en objet unique.",format:"Voix off + macro produit",duration:"45 s",problem:"Le travail inclus dans une création sur mesure reste souvent invisible.",hook:"Cette bague n’existait pas il y a encore sept jours.",beats:["Croquis et demande du client.","Fonte du métal puis travail à l’établi.","Sertissage et polissage en macro.","CTA : « Quelle histoire aimeriez-vous porter ? »"]},
{id:"12",title:"Le meuble qui gagne 4 m²",category:"artisan",sector:"Menuiserie",objective:"Générer des demandes de devis",angle:"Vendre le résultat concret plutôt que seulement le beau matériau.",format:"Avant/après commenté",duration:"30 s",problem:"Le prospect visualise difficilement le gain d’un aménagement sur mesure.",hook:"Ce mur vide faisait perdre quatre mètres carrés à cette pièce.",beats:["Plan avant avec mesure à l’écran.","Découpe et assemblage à l’atelier.","Installation accélérée.","CTA : « Montrez-nous votre espace perdu. »"]},
{id:"13",title:"Le bouquet qui dure plus longtemps",category:"artisan",sector:"Fleuriste",objective:"Promouvoir un service premium",angle:"Donner un conseil utile avant de présenter le bouquet.",format:"Démonstration face caméra",duration:"30 s",problem:"Les clients hésitent à payer plus sans comprendre la fraîcheur et l’entretien.",hook:"Le premier geste à faire avec vos fleurs n’est pas de les mettre dans l’eau.",beats:["Recoupe des tiges en biais.","Retrait des feuilles sous la ligne d’eau.","Composition du bouquet de saison.","CTA : « Passez en boutique, on prépare le vôtre. »"]},
{id:"14",title:"De la terre à votre table",category:"artisan",sector:"Céramiste",objective:"Vendre une collection",angle:"Montrer la transformation lente de la matière.",format:"ASMR atelier + texte",duration:"30 s",problem:"Une pièce artisanale est comparée à de la vaisselle produite en série.",hook:"Avant d’être une tasse, c’était simplement 400 grammes de terre.",beats:["Pesée puis centrage de la terre.","Forme qui apparaît sur le tour.","Émaillage et sortie du four.","CTA : « La nouvelle collection est disponible en quantité limitée. »"]},
{id:"15",title:"Ce mur cachait un problème",category:"artisan",sector:"Artisan rénovateur",objective:"Créer de la confiance",angle:"Expliquer une décision technique qui évite un futur problème.",format:"Chantier commenté",duration:"45 s",problem:"Le client voit le résultat mais peine à évaluer la qualité invisible.",hook:"On devait repeindre ce mur. On a découvert pourquoi il ne fallait surtout pas le faire.",beats:["Mur avant travaux et première inspection.","Révélation de l’humidité derrière le revêtement.","Traitement et reprise expliqués simplement.","CTA : « Avant de masquer un problème, faisons le bon diagnostic. »"]},

{id:"16",title:"Le produit qui part en deux jours",category:"commerce",sector:"Épicerie indépendante",objective:"Générer du trafic en boutique",angle:"Utiliser la preuve sociale et une disponibilité limitée.",format:"Face caméra en rayon",duration:"15 s",problem:"Une nouveauté passe inaperçue auprès des visiteurs occasionnels.",hook:"On le reçoit le mardi. Le jeudi, il n’en reste presque jamais.",beats:["Le commerçant prend le produit en rayon.","Une phrase sur son origine.","Client qui le place dans son panier.","CTA : « Le prochain arrivage, c’est mardi. »"]},
{id:"17",title:"Un cadeau qui ne finira pas au placard",category:"commerce",sector:"Concept store",objective:"Augmenter les ventes cadeaux",angle:"Partir de la peur de choisir un cadeau impersonnel.",format:"Sélection face caméra",duration:"30 s",problem:"Les clients manquent d’idées et achètent au dernier moment.",hook:"Si vous ne connaissez pas sa taille, ses goûts ou sa couleur préférée, commencez ici.",beats:["Trois profils de destinataires à l’écran.","Une idée de cadeau pour chacun.","Emballage offert en plan rapide.","CTA : « Dites-nous pour qui, on vous aide à choisir. »"]},
{id:"18",title:"Le livre que je conseille sans hésiter",category:"commerce",sector:"Librairie",objective:"Créer une visite en boutique",angle:"Une recommandation personnelle plutôt qu’un résumé classique.",format:"Libraire face caméra",duration:"30 s",problem:"Les recommandations en ligne ne remplacent pas le conseil humain.",hook:"J’ai vendu ce livre 47 fois, mais jamais pour la même raison.",beats:["Le livre apparaît sans dévoiler la couverture immédiatement.","Trois types de lecteurs auxquels il convient.","Révélation de la couverture.","CTA : « Passez me dire ce que vous aimez lire. »"]},
{id:"19",title:"Vos lunettes ne devraient pas glisser",category:"commerce",sector:"Opticien",objective:"Promouvoir l’ajustement en magasin",angle:"Résoudre une gêne quotidienne en moins de trente secondes.",format:"Conseil + démonstration",duration:"30 s",problem:"Les clients ignorent qu’un ajustement simple peut améliorer leur confort.",hook:"Si vous remontez vos lunettes dix fois par jour, ce n’est pas normal.",beats:["Démonstration du problème.","Contrôle des branches et des plaquettes.","Ajustement rapide en atelier.","CTA : « Passez en boutique, on vérifie gratuitement. »"]},
{id:"20",title:"Le vélo que vous avez déjà",category:"commerce",sector:"Magasin de vélos",objective:"Vendre un entretien",angle:"Montrer qu’une révision peut éviter un achat prématuré.",format:"Diagnostic atelier",duration:"45 s",problem:"Le client pense que son vélo est trop vieux alors qu’il est surtout mal entretenu.",hook:"Vous n’avez peut-être pas besoin d’un nouveau vélo.",beats:["Vélo bruyant présenté avant intervention.","Trois points de contrôle visibles.","Réglage, lubrification et essai.","CTA : « Faites diagnostiquer le vôtre avant de le remplacer. »"]},

{id:"21",title:"La coupe que vous ne demandiez pas",category:"service",sector:"Salon de coiffure",objective:"Obtenir des rendez-vous",angle:"Montrer la valeur d’un diagnostic personnalisé.",format:"Dialogue + avant/après",duration:"30 s",problem:"Les prospects ne savent pas quelle coupe leur conviendra vraiment.",hook:"Vous n’avez peut-être pas besoin de la coupe que vous aviez choisie.",beats:["La cliente montre sa photo de référence.","Diagnostic : visage, texture et entretien.","Étapes clés en montage rapide.","CTA : « Réservez votre diagnostic. »"]},
{id:"22",title:"Pourquoi ce bien ne se vend pas",category:"service",sector:"Agence immobilière",objective:"Obtenir des mandats",angle:"Expliquer une erreur fréquente avec une preuve visuelle.",format:"Agent face caméra + visite",duration:"45 s",problem:"Les propriétaires hésitent à demander un accompagnement professionnel.",hook:"Ce bien est en ligne depuis quatre mois. Le problème tient en trois photos.",beats:["Capture anonymisée de l’annonce.","Comparaison entre anciennes et nouvelles photos.","Explication du repositionnement.","CTA : « Votre annonce bloque ? Demandons-nous pourquoi. »"]},
{id:"23",title:"Votre première séance commence ici",category:"service",sector:"Coach sportif",objective:"Convertir des débutants",angle:"Lever la peur de ne pas avoir le niveau.",format:"Face caméra + séance réelle",duration:"30 s",problem:"Les prospects repoussent leur inscription car ils pensent devoir déjà être en forme.",hook:"Vous n’avez pas besoin d’être en forme pour commencer. C’est justement le but.",beats:["Accueil d’un débutant.","Mouvement adapté et correction bienveillante.","Progression mesurable affichée.","CTA : « Réservez votre séance découverte. »"]},
{id:"24",title:"Le bureau propre avant 8 h",category:"service",sector:"Entreprise de nettoyage",objective:"Obtenir des devis professionnels",angle:"Montrer la fiabilité à travers une contrainte horaire réelle.",format:"Coulisses chronométrées",duration:"30 s",problem:"Le nettoyage professionnel paraît interchangeable jusqu’au premier incident.",hook:"À 7 h 12, tout doit être impeccable. Les premiers salariés arrivent à 8 h.",beats:["Équipe qui entre dans les locaux vides.","Répartition des zones et contrôles.","Dernier passage à 7 h 52.","CTA : « Besoin d’une équipe qui tient ses horaires ? Parlons-en. »"]},
{id:"25",title:"La ligne qui coûte cher",category:"service",sector:"Expert-comptable",objective:"Générer des rendez-vous",angle:"Rendre un sujet financier concret avec un exemple simple.",format:"Face caméra + chiffres écran",duration:"30 s",problem:"Les dirigeants ne voient pas toujours l’intérêt d’un conseil avant l’erreur.",hook:"Cette ligne de votre tableau peut vous coûter plus cher que votre loyer.",beats:["Une ligne floutée du tableau est pointée.","Explication simple de l’erreur fréquente.","Conséquence chiffrée avec exemple fictif clairement indiqué.","CTA : « Faites vérifier vos chiffres avant la prochaine échéance. »"]},

{id:"26",title:"Le lancer qui change la partie",category:"loisirs",sector:"Bowling",objective:"Augmenter les réservations en groupe",angle:"Transformer une sortie classique en défi immédiat entre amis.",format:"POV + montage rythmé",duration:"30 s",problem:"Le bowling est parfois perçu comme une activité déjà connue et sans surprise.",hook:"Vous avez un seul lancer pour choisir qui paie la prochaine partie.",beats:["Gros plan sur les quilles et la boule saisie.","Les amis annoncent leur pronostic face caméra.","Ralenti du lancer puis réaction du groupe.","CTA : « Réservez votre piste et lancez votre propre défi. »"]},
{id:"27",title:"Le plat qui change chaque semaine",category:"restauration",sector:"Food truck",objective:"Créer du trafic sur un emplacement",angle:"Utiliser la nouveauté et la disponibilité limitée pour déclencher une visite.",format:"Coulisses + voix off",duration:"30 s",problem:"Les clients potentiels ne savent pas toujours où trouver le food truck ni ce qui est servi.",hook:"Ce plat disparaît dimanche soir, et il ne reviendra peut-être jamais.",beats:["Préparation du produit phare en gros plans.","Présentation rapide de l’ingrédient signature.","Adresse et horaires affichés clairement.","CTA : « Venez le goûter avant dimanche. »"]},
{id:"28",title:"Le cuir qui raconte votre histoire",category:"artisan",sector:"Maroquinerie",objective:"Valoriser le sur-mesure",angle:"Montrer comment un objet personnel naît de gestes précis.",format:"Plans atelier + voix off",duration:"45 s",problem:"Le prix d’une pièce artisanale paraît élevé quand le travail reste invisible.",hook:"Avant de devenir votre sac, cette pièce passe entre mes mains plus de cent fois.",beats:["Choix et découpe du cuir.","Couture, teinture de tranche et pose des finitions.","Initiales du client marquées sur la pièce.","CTA : « Parlons de la pièce que vous garderez des années. »"]},
{id:"29",title:"Le jouet que votre chien choisit",category:"commerce",sector:"Animalerie indépendante",objective:"Générer des visites en boutique",angle:"Faire du conseil personnalisé une expérience amusante.",format:"Test produit en magasin",duration:"30 s",problem:"Les produits semblent interchangeables sans démonstration ni conseil.",hook:"On a laissé trois jouets devant lui. Il n’a pas hésité une seconde.",beats:["Trois jouets sont posés au sol.","Le chien fait son choix et commence à jouer.","Le commerçant explique pour quel profil il convient.","CTA : « Venez trouver celui qui correspond au vôtre. »"]},
{id:"30",title:"Votre première heure de conduite",category:"service",sector:"Auto-école",objective:"Obtenir des inscriptions",angle:"Rassurer les débutants en montrant une progression simple et encadrée.",format:"Face caméra + mise en situation",duration:"45 s",problem:"La peur de conduire retarde souvent l’inscription des futurs élèves.",hook:"Si vos mains tremblent avant même de démarrer, cette première heure est faite pour vous.",beats:["Accueil calme de l’élève dans la voiture à l’arrêt.","Réglages du siège, des rétroviseurs et rappel des commandes.","Premier démarrage sur une zone adaptée.","CTA : « Réservez votre évaluation sans pression. »"]}
];

const grid=document.querySelector('#scriptGrid'),empty=document.querySelector('#emptyState'),dialog=document.querySelector('#scriptDialog'),content=document.querySelector('#dialogContent'),featuredIds=new Set(['01','06','11','16','21','27']);let filter='featured';
function render(){const visible=scripts.filter(s=>filter==='featured'?featuredIds.has(s.id):s.category===filter);grid.innerHTML=visible.map(s=>`<article class="project" tabindex="0" data-id="${s.id}" aria-label="Lire le script ${s.title}"><div class="project-meta"><span>${s.id}</span><span>${s.sector}</span><span>${s.duration}</span></div><h3>${s.title}</h3><p class="problem"><b>Problème</b> ${s.problem}</p><p class="idea"><b>Idée</b> ${s.angle}</p><div class="project-bottom"><span>${s.objective}</span><b class="read-link">Lire le script</b></div></article>`).join('');empty.hidden=visible.length>0;}
function openScript(id){const s=scripts.find(x=>x.id===id);content.innerHTML=`<span class="modal-label">${s.sector} • ${s.duration}</span><h3 id="dialogTitle">${s.title}</h3><div class="modal-grid"><div><small>OBJECTIF</small><b>${s.objective}</b></div><div><small>ANGLE</small><b>${s.angle}</b></div><div><small>FORMAT</small><b>${s.format}</b></div><div><small>DURÉE</small><b>${s.duration}</b></div></div><h4>ACCROCHE</h4><blockquote>« ${s.hook} »</blockquote><h4>SCRIPT</h4><ol class="script-steps">${s.beats.map((b,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><p>${b}</p></li>`).join('')}</ol><p class="modal-note">Exemple de portfolio. Le script final est adapté aux preuves, aux offres et au ton de chaque entreprise.</p>`;dialog.showModal()}
grid.addEventListener('click',e=>{const card=e.target.closest('.project');if(card)openScript(card.dataset.id)});grid.addEventListener('keydown',e=>{const card=e.target.closest('.project');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openScript(card.dataset.id)}});
document.querySelectorAll('.filters button').forEach(btn=>{const count=btn.dataset.filter==='featured'?featuredIds.size:scripts.filter(s=>s.category===btn.dataset.filter).length;btn.textContent=`${btn.textContent} (${count})`;btn.addEventListener('click',()=>{document.querySelector('.filters .active').classList.remove('active');btn.classList.add('active');filter=btn.dataset.filter;render()})});document.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});render();
const nav=document.querySelector('#nav'),navLinks=[...document.querySelectorAll('#mainNav a')],menu=document.querySelector('.menu-toggle'),mainNav=document.querySelector('#mainNav');const updateNav=()=>nav.classList.toggle('scrolled',window.scrollY>20);window.addEventListener('scroll',updateNav,{passive:true});updateNav();menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));mainNav.classList.toggle('open',!open)});navLinks.forEach(a=>a.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');mainNav.classList.remove('open')}));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)navLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${entry.target.id}`))}),{rootMargin:'-25% 0px -65% 0px'});document.querySelectorAll('main section[id]').forEach(s=>observer.observe(s));
document.querySelector('#contactForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),subject=`Demande Studio Local — ${d.get('entreprise')}`,body=`Bonjour Noam,\n\nEntreprise : ${d.get('entreprise')}\nSecteur : ${d.get('secteur')}\nObjectif : ${d.get('objectif')}\nRéseau social : ${d.get('reseau')}\nType de contenu : ${d.get('contenu')}\n\nJe souhaite recevoir une première idée pour mon entreprise.`;window.location.href=`mailto:noamlagedamont@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;document.querySelector('#formNote').textContent='Votre application e-mail va s’ouvrir avec le message préparé.'});

// Progressive motion: smooth, subtle and disabled when the visitor asks for reduced motion.
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const progress=document.createElement('div');progress.className='scroll-progress';progress.setAttribute('aria-hidden','true');document.body.prepend(progress);
let scrollTick=false;const updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?Math.min(scrollY/max,1):0})`;scrollTick=false};
window.addEventListener('scroll',()=>{if(!scrollTick){requestAnimationFrame(updateProgress);scrollTick=true}},{passive:true});updateProgress();

const revealObserver=reduceMotion?null:new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -45px'});
const addReveal=(elements)=>elements.forEach((el,index)=>{el.classList.add('reveal');if(index%4)el.classList.add(`reveal-delay-${index%4}`);if(revealObserver)revealObserver.observe(el);else el.classList.add('is-visible')});
addReveal([...document.querySelectorAll('.section-head,.process-intro,.difference .shell,.contact-grid>div,.contact-grid form,.deliverable-grid article,.process li,.faq-list details,.value-strip .shell>div')]);
const revealProjects=()=>addReveal([...document.querySelectorAll('.project:not(.reveal)')]);revealProjects();new MutationObserver(revealProjects).observe(grid,{childList:true});

const preview=document.querySelector('.script-preview');if(preview&&!reduceMotion&&matchMedia('(pointer:fine)').matches){preview.addEventListener('pointermove',e=>{const r=preview.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;preview.style.transform=`perspective(900px) rotateX(${y*-2.5}deg) rotateY(${x*3.5}deg) translateY(-2px)`});preview.addEventListener('pointerleave',()=>preview.style.transform='')}

document.querySelectorAll('.filters button').forEach(button=>button.setAttribute('aria-pressed',String(button.classList.contains('active'))));
document.querySelector('.filters').addEventListener('click',e=>{if(e.target.matches('button'))document.querySelectorAll('.filters button').forEach(button=>button.setAttribute('aria-pressed',String(button===e.target)))});
window.addEventListener('resize',updateProgress,{passive:true});
